version: '3.8'

services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: tvarit_special_sum
    env_file:
      - .env
    ports:
      - 5000:5000
    network_mode: "host"
    volumes:
      - .:/code
    command: python app.py